# netlify.toml  
[build]
  base    = "parking"                               
  command = "corepack enable && corepack prepare pnpm@latest --activate && pnpm install && pnpm run build"
  publish = "dist/static"                           # Vite 的输出目录

[build.environment]
  NODE_VERSION = "20"
  VITE_API_BASE = "http://54.227.183.166:8000/api" 

# SPA 刷新路由不 404
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200

# 静态资源缓存（可选）
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"